#RBAC in kubernetes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: expense-trainee
  namespace: expense
rules:
- apiGroups: [""]
  resources: ["pods"]   #only pods previleges to trainee suresh (reources  --Nouns)
  verbs: ["get", "watch", "list"]   #actions (verbs) 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: expense-trainee
  namespace: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: expense-trainee
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: suresh