#Copy and paste : kubectl get configmap aws-auth -n kube-system -o yaml  (yaml code)
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::537124943253:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-uchUFma4aeAx
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |    #Add this user (google: aws auth config eks)
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::537124943253:user/suresh
      username: suresh
    - groups:
      - expense-admin
      userarn: arn:aws:iam::537124943253:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-08T05:28:58Z"
  name: aws-auth
  namespace: kube-system
  # resourceVersion: "2098"  #remove (new version will cfaete )
  uid: 5ad4f822-5774-498f-bd7e-321f60b6452d
